.Dd $Mdocdate: September 13 2022 $
.Dt PIZAUTH.CONF 5
.Os
.Sh NAME
.Nm pizauth.conf
.Nd pizauth configuration file
.Sh DESCRIPTION
.Nm
is the configuration file for
.Xr pizauth 1 .
.Pp
The top-level options are:
.Bl -tag -width Ds
.It Sy auth_notify_cmd = Qo Em shell-cmd Qc ;
specifies a shell command to be run via
.Ql $SHELL -c
when an account needs to be authenticated.
Two special environment variables are set:
.Em $PIZAUTH_ACCOUNT
is set to the account name;
.Em $PIZAUTH_URL
is set to the URL required to authorise the account.
Optional.
.It Sy auth_notify_interval = Em time ;
specifies the gap between reminders to the user of authentication requests.
Defaults to 15 minutes if not specified.
.It Sy error_notify_cmd = Qo Em shell-cmd Qc ;
specifies a shell command to be run via
.Ql $SHELL -c
when an error has occurred when authenticating an account.
Two special environment variables are set:
.Em $PIZAUTH_ACCOUNT
is set to the account name;
.Em $PIZAUTH_MSG
is set to the error message.
Defaults to logging via
.Xr syslog 3
if not specified.
.It Sy http_listen = Qo Em bind-name Qc ;
specifies the address for the
.Xr pizauth 1
HTTP server to listen on.
Defaults to
.Qq 127.0.0.1:0 .
.It Sy not_transient_error_if = Qo Em shell-cmd Qc ;
specifies a shell command to be run when pizauth repeatedly encounters
errors when trying to refresh a token.
If
.Em shell-cmd
returns a zero exit code, or exceeds a 3 minute timeout, pizauth treats
the errors as permanent: the access token is invalidated (forcing the user
to later reauthenicate).
If
.Em shell-cmd
returns a non-zero exit code, the transient errors are ignored.
Defaults to ignoring non-fatal errors if not specified.
.It Sy refresh_at_least = Em time ;
specifies the maximum period of time before an access token will be forcibly
refreshed.
Defaults to 90 minutes if not specified.
.It Sy refresh_before_expiry = Em time ;
specifies how far in advance an access token should be refreshed before it
expires.
Defaults to 90 seconds if not specified.
.It Sy refresh_retry = Em time ;
specifies the gap between retrying refreshing after transitory errors
(e.g. due to network problems).
Defaults to 40 seconds if not specified.
.It Sy token_event_cmd = Qo Em shell-cmd Qc ;
specifies a shell command to be run via
.Ql $SHELL -c
when an account's access token changes state.
Two special environment variables are set:
.Em $PIZAUTH_ACCOUNT
is set to the account name;
.Em $PIZAUTH_EVENT
is set to the event type.
The event types are:
.Em token_invalidated
if a previously valid access token is invalidated;
.Em token_new
if a new access token is obtained;
.Em token_refreshed
if an access token is refreshed.
Token events are queued and processed one-by-one in the order they were
received: at most one instance of
.Sy token_event_cmd
will be executed at any point in time; and there is no guarantee
that an event reflects the current state of an account's access token,
since further events may be stored in the queue.
Note that
.Sy token_event_cmd
is subject to a 10 second timeout.
Optional.
.El
.Pp
An
.Sq account
block supports the following options:
.Bl -tag -width Ds
.It Sy auth_uri = Qo Em URI Qc ;
where
.Em URI
is a URI specifying the OAuth2 server's authentication URI.
Mandatory.
.It Sy auth_uri_fields = { Qo Em Key 1 Qc : Qo Em Val 1 Qc , ..., Qo Em Key n Qc : Qo Val n Qc } ;
specifies zero or more query fields to be passed to
.Sy auth_uri
after any fields that
.Nm
may have added itself.
Keys (and their values) are added to
.Sy auth_uri
in the order they appear in
.Sy auth_uri_fields ,
each separated by
.Qq & .
The same key may be specified multiple times.
Optional.
.It Sy client_id = Qo Em ID Qc ;
specifies the OAuth2 client ID (i.e. the identifier of the client software).
Mandatory.
.It Sy client_secret = Qo Em Secret Qc ;
specifies the OAuth2 client secret (similar to the
.Em client_id ) .
Optional.
.It Sy login_hint = Qo Em Hint Qc ;
is used by the authentication server to help the user understand which account
they are authenticating.
Typically a username or email address.
Optional.
.Em Deprecated :
use
.Ql auth_uri_fields = { Qo login_hint Qc : Qo Hint Qc }
instead.
.It Sy not_transient_error_if = Qo Em shell-cmd Qc ;
Overrides the global
.Sy not_transient_error_if
option for this account.
Follows the same format as the global option.
.It Sy redirect_uri = Qo Em URI Qc ;
where
.Em URI
is a URI specifying the OAuth2 server's redirection URI.
Defaults to
.Qq http://localhost/
if not specified.
.It Sy refresh_at_least = Em time ;
Overrides the global
.Sy refresh_at_least
option for this account.
Follows the same format as the global option.
.It Sy refresh_before_expiry = Em time ;
Overrides the global
.Sy refresh_before_expiry
option for this account.
Follows the same format as the global option.
.It Sy refresh_retry = Em time ;
Overrides the global
.Sy refresh_retry
option for this account.
Follows the same format as the global option.
.It Sy scopes = [ Qo Em Scope 1 Qc , ..., Qo Em Scope n Qc ] ;
specifies zero or more OAuth2 scopes (roughly speaking,
.Qq permissions )
that access tokens will give you permission to utilise.
Optional.
.It Sy token_uri = Qo Em URI Qc ;
is a URI specifying the OAuth2 server's token URI.
Mandatory.
.El
.Pp
Times can be specified as
.Em int [smhd]
where the suffixes mean (in order): seconds, minutes, hours, days.
For example,
.Em 90s
means 90 seconds and
.Em 5m
means 5 minutes.
.Sh EXAMPLES
An example
.Nm
file for accessing IMAP and SMTP services in Office365
is as follows:
.Bd -literal -offset 4n
account "officesmtp" {
    auth_uri = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize";
    token_uri = "https://login.microsoftonline.com/common/oauth2/v2.0/token";
    client_id = "..."; // Fill in with your Client ID
    client_secret = "..."; // Fill in with your Client secret
    scopes = [
      "https://outlook.office365.com/IMAP.AccessAsUser.All",
      "https://outlook.office365.com/SMTP.Send",
      "offline_access"
    ];
    // You don't have to specify login_hint, but it does make
    // authentication a little easier.
    auth_uri_fields = { "login_hint": "email@example.com" };
}
.Ed
.Pp
Note that Office365 requires the non-standard
.Qq offline_access
scope to be specified in order for
.Xr pizauth 1
to be able to operate successfully.
.Sh SEE ALSO
.Xr pizauth 1
.Pp
.Lk https://tratt.net/laurie/src/pizauth/
.Sh AUTHORS
.An -nosplit
.Xr pizauth 1
was written by
.An Laurence Tratt Lk https://tratt.net/laurie/
