.Dd $Mdocdate: September 13 2022 $
.Dt PIZAUTH 1
.Os
.Sh NAME
.Nm pizauth
.Nd OAuth2 authentication daemon
.Sh SYNOPSIS
.Nm pizauth
.Ar Sy refresh | Sy reload | Sy server | Sy show | Sy shutdown
.Op Ar options ...
.Sh DESCRIPTION
.Nm
obtains, hands out, and refreshes OAuth2 tokens.
It is formed of two
components: a persistent "server" which interacts with the user to obtain
tokens, and refreshes them as necessary; and a command-line interface which can
be used by other programs to show the OAuth2 token for a current account.
.Pp
The top-level commands are:
.Bl -tag -width Ds
.It Sy refresh Oo Fl u Oc Ar account
Attempt to refresh the access token for
.Em account .
If there is not currently a valid access or refresh token, reports an error
and initiates a new token request.
Unless
.Fl u
is specified, the error will include an authorization URL.
.It Sy reload
Reload the server's configuration.
.It Sy server Oo Fl c Ar config-file Oc Oo Fl d Oc
Start the server.
If not specified with
.Fl c ,
.Nm
checks for the configuration file (in order) at:
.Pa $XDG_CONFIG_HOME/pizauth.conf ,
.Pa $HOME/.config/pizauth.conf .
The server will daemonise itself unless
.Fl d
is specified.
.It Sy show Oo Fl u Oc Ar account
Prints the current access token for
.Em account
to stdout.
If there is not currently a valid access token, prints an error to stderr.
If refreshing might obtain a valid access token, refreshing is initiated.
Otherwise (unless
.Fl u
is specified), the error will include an authorization URL.
Note that this command does not block: commands must expect that they might
encounter an error when showing an access token.
.It Sy shutdown
Shut the server down.
Note that shutdown occurs asynchronously: the server may still be alive for a
period of time after this command returns.
.El
.Sh SEE ALSO
.Xr pizauth.conf 5
.Pp
.Lk https://tratt.net/laurie/src/pizauth/
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Laurence Tratt Aq https://tratt.net/laurie/
