name: CI

on:
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: rustup component add rustfmt
    - run: cargo fmt --all --check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - name: Linux x86_64 stable
          os: ubuntu-latest
          rust: stable
          other: i686-unknown-linux-gnu
        - name: Linux x86_64 beta
          os: ubuntu-latest
          rust: beta
          other: i686-unknown-linux-gnu
        - name: Linux x86_64 nightly
          os: ubuntu-latest
          rust: nightly
          other: i686-unknown-linux-gnu
        - name: macOS x86_64 stable
          os: macos-latest
          rust: stable
          other: x86_64-apple-ios
    name: Tests ${{ matrix.name }}
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - name: debug_tests
      run: cargo test
    - name: release_tests
      run: cargo test --release
